name: qpc
version: 1.2.1+3
publish_to: none
description: Question pour un champion.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.2.1+2
  flutter: 
    sdk: flutter
  
  liquid_progress_indicator: ^0.4.0
  flutter_countdown_timer: ^4.1.0
  timer_count_down: ^2.2.0
  # dart_vlc: ^0.0.9
  intl: ^0.17.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/

